// SPDX-License-Identifier: GPL-3.0-or-later
// ~/.config/lifebar/config: key=value lines, generated by lifeconf from
// theme.toml (the seven palette roles, the font) and safe to hand-edit.
// Unknown keys are ignored; a missing file means the olive defaults.

use crate::cli::Rgba;

#[derive(Debug, Clone, PartialEq)]
pub struct Config {
    pub font: String,
    /// Pixels, as waybar's CSS font-size.
    pub size: f32,
    /// Logical pixels.
    pub height: u32,
    pub bg: Rgba,
    pub surface: Rgba,
    pub border: Rgba,
    pub text: Rgba,
    pub accent: Rgba,
    pub warn: Rgba,
    pub urgent: Rgba,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            font: "ShureTechMono Nerd Font".into(),
            size: 13.0,
            height: 26,
            bg: [0x12, 0x14, 0x12, 0xff],
            surface: [0x17, 0x1a, 0x14, 0xff],
            border: [0x39, 0x41, 0x2b, 0xff],
            text: [0x7b, 0x8c, 0x5a, 0xff],
            accent: [0xa4, 0xc9, 0x4b, 0xff],
            warn: [0xc9, 0xa2, 0x4b, 0xff],
            urgent: [0x8a, 0x3b, 0x2e, 0xff],
        }
    }
}

/// `RRGGBB` or `RRGGBBAA`, `#` optional.
pub fn parse_rgba(s: &str) -> Option<Rgba> {
    let s = s.trim().trim_start_matches('#');
    if !s.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    let v = u32::from_str_radix(s, 16).ok()?;
    match s.len() {
        6 => Some([(v >> 16) as u8, (v >> 8) as u8, v as u8, 0xff]),
        8 => Some([(v >> 24) as u8, (v >> 16) as u8, (v >> 8) as u8, v as u8]),
        _ => None,
    }
}

impl Config {
    pub fn parse(body: &str) -> Config {
        let mut c = Config::default();
        for line in body.lines() {
            let l = line.trim();
            if l.starts_with('#') {
                continue;
            }
            let Some((k, v)) = l.split_once('=') else { continue };
            let v = v.trim();
            let col = |cur: Rgba| parse_rgba(v).unwrap_or(cur);
            match k.trim() {
                "font" if !v.is_empty() => c.font = v.to_string(),
                "size" => c.size = v.parse().unwrap_or(c.size),
                "height" => c.height = v.parse().unwrap_or(c.height),
                "bg" => c.bg = col(c.bg),
                "surface" => c.surface = col(c.surface),
                "border" => c.border = col(c.border),
                "text" => c.text = col(c.text),
                "accent" => c.accent = col(c.accent),
                "warn" => c.warn = col(c.warn),
                "urgent" => c.urgent = col(c.urgent),
                _ => {}
            }
        }
        c.size = c.size.clamp(6.0, 48.0);
        c.height = c.height.clamp(12, 120);
        c
    }

    pub fn path() -> Option<String> {
        let base = std::env::var("XDG_CONFIG_HOME")
            .ok()
            .filter(|s| !s.is_empty())
            .or_else(|| std::env::var("HOME").ok().map(|h| format!("{h}/.config")))?;
        Some(format!("{base}/lifebar/config"))
    }

    pub fn load() -> Config {
        Config::path().and_then(|p| std::fs::read_to_string(p).ok()).map(|b| Config::parse(&b)).unwrap_or_default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_what_lifeconf_writes_and_ignores_the_rest() {
        let c = Config::parse("# generated\nfont=Cousine Nerd Font\nsize=14\nheight=30\naccent=#ff0000\nwarn=00ff0080\nbogus=1\ntext=nothex\n");
        assert_eq!((c.font.as_str(), c.size, c.height), ("Cousine Nerd Font", 14.0, 30));
        assert_eq!(c.accent, [255, 0, 0, 255]);
        assert_eq!(c.warn, [0, 255, 0, 0x80]);
        assert_eq!(c.text, Config::default().text, "a bad colour keeps the default");
        assert_eq!(Config::parse("size=1000\nheight=0").size, 48.0);
    }
}
